server:
  port: 8080
  servlet:
    context-path: /api/v1
jwt:
  secret: ${random.value}
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka
    registerWithEureka: true
    fetchRegistry: true

amqp:
  auth-validation:
    queue:
      request: auth-validation-req
      response: auth-validation-res
    exchange:
      response: auth-validation-res-exchange
  user-manager-registration:
    queue: user-manager-registration
    exchange: registration

spring:
  application:
    name: Authentication-Service
