spring:
  datasource:
    url: jdbc:h2:mem:authDb
    username: Schrodingdong
    password: Schrodingdong
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect