server:
  port: 8080
  servlet:
    context-path: /api/v1
jwt:
  secret: ${JWT_SECRET}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true

amqp:
  auth-validation:
    queue:
      request: auth-validation-req
      response: auth-validation-res
    exchange:
      response: auth-validation-res-exchange

spring:
  application:
    name: Authentication-Service
