server:
  servlet:
    context-path: /api/v1
  port: 8081
jwt:
  secret: ${JWT_SECRET}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
spring:
  application:
    name: Authentication-Service
