version: '3.0'

volumes:
  postgres-data:
  neo4j-data:
  mongo-data:


services:
  api-gateway:
    container_name: api-gateway
    image: project-k-api-gateway
    ports:
      - 8888:8888
  discovery:
    container_name: discovery
    image: project-k-discovery
    ports:
      - 8761:8761
  authentication:
    container_name: authentication
    image: project-k-authentication
    ports:
      - 8080:8080
    environment:
        - SPRING_PROFILES_ACTIVE=production
        - POSTGRES_DB=authentication-db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    depends_on:
        - postgres
        - api-gateway
        - discovery
  user-manager:
    container_name:  user-manager
    image: project-k-user-manager
    ports:
      - 8081:8081
    depends_on:
      - neo4j
      - api-gateway
      - discovery
  quote-manager:
    container_name: quote-manager
    image: project-k-quote-manager
    ports:
      - 8082:8082
    depends_on:
      - mongo-db
      - api-gateway
      - discovery
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=authentication-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  neo4j:
    container_name: neo4j
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
        - neo4j-data:/data
    environment:
        - NEO4J_AUTH=neo4j/saga-pablo-lagoon-java-license-4169
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  mongo-db:
    container_name: mongo-db
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

