server:
  port: 8082
  servlet:
    context-path: /api/v1

spring:
  application:
    name: user-manager-service
  neo4j:
    uri: bolt://neo4j:7687
    authentication:
      username: neo4j
      password: smoke-cake-cowboy-herbert-carpet-2714
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
amqp:
  user-manager-registration:
    queue: user-manager-registration
  user-following:
    queue: quote-user-following-q