spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
    discovery:
      enabled: true
  rabbitmq:
    host: localhost #change to rabbitmq when dockerized
    port: 5672
    username: guest
    password: guest

amqp:
  auth-validation:
    queue:
      request: auth-validation-req
      response: auth-validation-res
    exchange:
      request: auth-validation-req-exchange

server:
  port: 8888

