spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: projectK

  application:
    name: quote-manager-service
issuer-bypass: "!Buw#Qu[Ps0.+Rk"
server:
  servlet:
    context-path: /api/v1
  port: 8081
